# Generated by Django 5.0.4 on 2024-07-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('auth_domain', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=255)),
                ('storage_bucket', models.CharField(max_length=255)),
                ('messaging_sender_id', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('measurement_id', models.CharField(max_length=255)),
                ('vapid_key', models.CharField(max_length=255)),
            ],
        ),
    ]
